services:
  database:
    build:
      context: .
      dockerfile: Lor.DatabaseApp/Presentation/DatabaseApp.WebApi/Dockerfile
    ports:
      - "31401:31401"
    environment:
      - ConnectionStrings:Redis=redis:31409
      - ASPNETCORE_URLS=${DATABASE_COMMUNICATION_URL}
      - ASPNETCORE_ENVIRONMENT=Production

  telegrambot:
    build:
      context: .
      dockerfile: Lor.TelegramBotApp/Presentation/TelegramBotApp.Api/Dockerfile
    environment:
      - TelegramSettings:BotToken=${TELEGRAM_BOT_TOKEN}
      - Profiles:Database-http:ApplicationUrl=${DATABASE_COMMUNICATION_URL}

  groupschedule:
    build:
      context: .
      dockerfile: Lor.GroupScheduleApp/Presentation/GroupScheduleApp.Api/Dockerfile
    environment:
      - Profiles:Database-http:ApplicationUrl=${DATABASE_COMMUNICATION_URL}