services:
  telegrambot:
    build:
      context: .
      dockerfile: Lor.TelegramBotApp/Presentation/TelegramBotApp.Api/Dockerfile
    environment:
      - TelegramSettings:BotToken=${TELEGRAM_BOT_TOKEN}
      - Profiles:Database-http:ApplicationUrl=${DATABASE_COMMUNICATION_URL}

  database:
    build:
      context: .
      dockerfile: Lor.DatabaseApp/Presentation/DatabaseApp.WebApi/Dockerfile
    ports:
      - "31401:31401"
    environment:
      - ConnectionStrings:Redis=redis:31409
      - ASPNETCORE_URLS=${DATABASE_COMMUNICATION_URL}
      - ASPNETCORE_ENVIRONMENT=Production

  redis:
    image: redis:latest
    ports:
      - "31409:31409"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 15s
      retries: 3