services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=31400
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "31400:31400"

  databaseapp:
    build:
      context: .
      dockerfile: Lor.DatabaseApp/Presentation/DatabaseApp.WebApi/Dockerfile
    ports:
      - "31401:31401"
    environment:
      - ASPNETCORE_URLS=${DATABASE_COMMUNICATION_URL}
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:DefaultConnection=Host=database:31400;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

  telegrambot:
    build:
      context: .
      dockerfile: Lor.TelegramBotApp/Presentation/TelegramBotApp.Api/Dockerfile
    environment:
      - TelegramSettings:BotToken=${TELEGRAM_BOT_TOKEN}
      - Profiles:Database-http:ApplicationUrl=${DATABASE_COMMUNICATION_URL}
      - ConnectionStrings:Redis=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  groupschedule:
    build:
      context: .
      dockerfile: Lor.GroupScheduleApp/Presentation/GroupScheduleApp.Api/Dockerfile
    environment:
      - Profiles:Database-http:ApplicationUrl=${DATABASE_COMMUNICATION_URL}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 15s
      retries: 3