name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types: [opened, synchronize]
    branches: [ main, dev ]

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build

      - name: Test DatabaseApp
        run: dotnet test Lor.DatabaseApp/Tests/DatabaseApp.Tests/DatabaseApp.Tests.csproj

  IntegrationTests:
    needs: UnitTests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Test DatabaseApp Integration
        run: dotnet test Lor.DatabaseApp/Tests/DatabaseApp.IntegrationTests/DatabaseApp.IntegrationTests.csproj